### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by jordanrule** [grantmd/space_station_god_game_proto_rust#3]
First off - I really like this idea.  We've been playing with Markov chains (another of your repos) in Java fashion for some time now and I feel they are getting a tad stale.

Would it be possible to add some basic instructions and simple stuff like win conditions to the README?  I feel it might make the repo more approachable.  If you like the idea but don't have time I'm happy to do so.

**Comment by grantmd** [comment]
Hey! So glad you like the idea. Unfortunately, as you probably gathered, this one is another abandoned project from me. It got to the point where I was having trouble coding things like "have this person eat this thing", and then read more about Entity Component Systems in Rust/game development, which solve that problem but would require a rewrite.

To get to your actual question: I didn't know what "win conditions" would look like at this point in the game, so I couldn't answer. Vaguely the idea was "keep the ship alive" but the actual mechanics were still something I was exploring.

Someday I'll revive this idea again, maybe with an ECS, and it will 100% succeed.
